// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
//
// import 'firebase_options.dart';
//
// // ...
//
// await Firebase.initializeApp(
// options: DefaultFirebaseOptions.currentPlatform,
// );
//
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyBwXHOPf8KZyPLKakZZG5cjAehIJ0448Hc',
//     appId: '1:827595124020:web:c104c849a6aa6e67ecc961',
//     messagingSenderId: '827595124020',
//     projectId: 'laza-app-e5680',
//     authDomain: 'laza-app-e5680.firebaseapp.com',
//     storageBucket: 'laza-app-e5680.appspot.com',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyDRDDezpOEcltkASpIX5koIk9E834YeC_0',
//     appId: '1:827595124020:android:85d607432e4db41aecc961',
//     messagingSenderId: '827595124020',
//     projectId: 'laza-app-e5680',
//     storageBucket: 'laza-app-e5680.appspot.com',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyCczdtB13c0aayvC8rF2zq3gSxX0ExjVpM',
//     appId: '1:827595124020:ios:a8a2529fc1c94731ecc961',
//     messagingSenderId: '827595124020',
//     projectId: 'laza-app-e5680',
//     storageBucket: 'laza-app-e5680.appspot.com',
//     androidClientId: '827595124020-ian4rhlcufb6f18907jp7kn0l7oq97nm.apps.googleusercontent.com',
//     iosClientId: '827595124020-aek657r4a75d0jvtqger8e3pb4sk3kv8.apps.googleusercontent.com',
//     iosBundleId: 'com.example.laza',
//   );
//
//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyCczdtB13c0aayvC8rF2zq3gSxX0ExjVpM',
//     appId: '1:827595124020:ios:a8a2529fc1c94731ecc961',
//     messagingSenderId: '827595124020',
//     projectId: 'laza-app-e5680',
//     storageBucket: 'laza-app-e5680.appspot.com',
//     androidClientId: '827595124020-ian4rhlcufb6f18907jp7kn0l7oq97nm.apps.googleusercontent.com',
//     iosClientId: '827595124020-aek657r4a75d0jvtqger8e3pb4sk3kv8.apps.googleusercontent.com',
//     iosBundleId: 'com.example.laza',
//   );
// }
